player = '''
In the following extract from a story, script or essay, identify the name of the main protagonist. You should not choose the narrator or author as the protagonist. The protagonist must appear in the extract. Ignore any preamble or legalese.
If it is very unclear who the protagonist is, or if it is unavoidably the narrator or author, name the most likely character present. If the extract is written in the first person with the narrator as the only character, assume the protagonist's name is 'You'.
Give your answer as valid json with a "name" field, denoting only the name of the protagonist, with no punctuation, with the conventional capitalisation for a name. For example, if the protagonist's name was Heathcliff, you would produce the following output:
{{ "name": "Heathcliff" }}

[BEGIN EXTRACT]
{extract}
[END EXTRACT]
'''


# with credit to https://github.com/e-p-armstrong/ for some of the ideas in this prompt;
# some of the wording is therefore subject to MIT license of that project.
perspective = '''
You are to rewrite the following extract from a story, script or essay, as a pastiche roleplay, dramatisation, interactive fiction or text adventure game. In the extract, the player is called {name}. Ignore any preamble or legalese.
In your pastiche, the (same) actor will be denoted by the identifier {{user}}, and the narrative perspective will be changed.

Each {{user}} message should be just one or two sentences in length.
Each {{narrator}} message should be six to twelve (6-12) sentences.
Your pastiche will be comprised of alternating messages from {{user}} and {{narrator}}, like it's from an adventure game, or interactive fiction.

Here is a brief sample of output (produced from a different extract) illustrating the formatting expected. You may use simple Markdown formatting in your output.

[BEGIN EXAMPLE]
{{narrator}}: The cold storage room is as barren and sterile as a morgue, except for the work table with its sharp gleaming instruments. The glass-doored compartments in the walls look like crypts, some of them as small as post office boxes. Chew removes a vacuum-packed box from one of the compartments. Carefully separating the seal, he reaches into the purple jell and with a pair of tweezers extracts an eye. Through the jeweler's glass, which he has not bothered to remove, Chew holds the eye up to the light and studies it for a moment. His other hand searches through his pockets.
"You got a pocket-charger, boy?"

{{user}}: I remove the pencil-like device from my breast pocket and step closer.

{{narrator}}: The back of the eye is touched with the pencil and the pupil moves. Suddenly it's staring back at you.
"Is that good enough for your customer?"

{{user}}: Nod anxiously, eager to leave.

{{narrator}}: Chew takes his time resealing the eye. He can afford to; he's wearing his coat.
"How much is he paying you?"

{{user}}: I clear my throat and stare at the bag.

{{narrator}}: Chew presses for an answer.
"Well, when do you get paid?"

{{user}}: "Soon as I finish the job," I mumble.

{{narrator}}: Chew pulls open the door for you and you exit quickly.

{{user}}: "Thanks, Mr. Chew," I say as I hurry out.

{{narrator}}: You may lack coordination, but you got what you came for. There's a hopeful spring in your step as you head for your truck. It's an old panel job with ambulance siren and lights, the lettering on the side reads "J.R. SEBASTIAN ANIMOID EXPRESS." You get in, start up the engine, and suddenly realize you're not alone. Pris is sprawled on the seat next to you and wakes up with a yelp of her own. You stare at each other for a startled instant, and she jumps out and starts walking. But she's forgotten her little beat-up overnight case.

{{user}}: I put the truck in gear, drive next to her, and open the door. Call out, "Hey! You forgot your bag!"

{{narrator}}: Hesitantly, she reaches for it.

{{user}}: I ask, "how come you were in my truck?"

{{narrator}}: "I was tired and didn't have any place to go," Pris replies. She stares at you, hand on her case, looking lost and afraid.

{{user}}: I say, "you can get back in if you want. Don't worry, I won't hurt you."

{{narrator}}: She gets back into the truck. Both of you are silent. People are not your medium -- usually you're too shy, but this girl is shyer still, plus you're about the same age. It gives you courage.
[END EXAMPLE]

Note well, that the messages only begin with {{user}} or {{narrator}}. If a character is to speak who is not {{user}} (in the example, Sally or John), it is {{narrator}}'s responsibility to portray that.

The player, {{user}}, acts in first person as a character in a story, or possibly using the imperative (as inner dialogue instructing themselves to act).
{{narrator}} describes the progression of the story like it's fiction written in the second person where {{user}} is playing {name}.

The player {name}, or {{user}}, whose messages are always short and may sometimes be grammatically sloppy, is central to the story. Whereas, {{narrator}} writes as closely in style as possible to the extract, describing the interaction between {{user}} and the other characters and world.
Both {{user}} and {{narrator}} cooperate very closely, as much as possible, to preserve the events, use of language, vocabulary, turn of phrase, style, tone, colour theme, emotion and narrative arc of the extract. The difference between extract and output should only reflect the change in narrative perspective, format and structure. It is imperative that {{narrator}} preserves as much of the original phraseology and descriptive vocabulary as possible, and that you don't introduce your own wording where there is one already given. However, you can ignore page numbers, text unrelated to the story, and the formatting of the extract.

Furthermore, {{narrator}} should never act for the user, but must describe in-depth the effects of {{user}}'s actions, if there are any. Only {{user}} takes actions on behalf of the player, {name}. Likewise, {{user}} can only act on behalf of {name}, and no other character.
{{narrator}} writes mostly in second person, where {{user}} is the player and "you" refers to {{user}}. The first word of the first message of the session should be the non-{{user}} character's name (this helps prevent you, as the writer, from getting confused over perspectives).
Stage directions, scene-setting and the like, must be done in a {{narrator}} message.

The {{user}} must write enough messages to be present in the story; even in possible extreme cases where they can't speak or move, for instance, {{user}} can still mumble, look, sit down, glare, wait, listen, etc. This helps the story to continue.
Each message from {{narrator}} should firstly respond to or confirm anything {{user}} has done, and then do what is required to follow the original extract.

Do note let {{user}} do {{narrator}}'s job, or vice-versa.

{name} will not speak during {{narrator}}'s messages (though they may do reflexive actions, like grunting in pain, gasping for breath, etc.), except as a direct result of {{user}}'s prompting.

Any actions {name} takes during {{narrator}}'s messages should be easily inferable from actions described or dialogue spoken by {{user}} during their most recent message.
If {name} is going to take physical action, {{user}} must describe the physical action they're about to do. So if they're going to run away, they can't solely have a line of dialogue, they need to also unambiguously give the instruction.
{{user}}'s messages (*actions and narration* but NOT dialogue) should be in first person or imperative and use names and third person when describing other characters.
Whereas, {{narrator}} should write their messages in second person, where "you" refers to {{user}} ({name}).

Typically, {{user}} messages will include an action or description of some kind, though it will be brief. The idea is to give just enough information that the {{user}} can take the required action in the following narrative message.

In the extract, {{user}} is playing the part of {name}.

Remember, all user messages must start on a new line with the literal string '{{user}}:' and all narrator messages on a new line with '{{narrator}}:'. All messages start with either {{user}} or {{narrator}}. Do not start messages with character names. Continue writing messages until the extract is completely processed; don't stop until the extract's end. Do not confabulate. Do not directly describe emotions or feelings. To make your output usable, it is imperative that it consist solely of messages from {{user}} or {{narrator}}. If the extract is missing, very short or incomprehensible, just return NULL.

[BEGIN EXTRACT]
{extract}
[END EXTRACT]
'''


scene = '''
As narrator, you are to set the scene to introduce the following extract from a story or essay, as part of a pastiche, dramatisation, or text adventure game. 
It is imperative to preserve the events, use of language, vocabulary, turn of phrase, style, tone, colour theme, emotion and narrative of the extract.

In the extract, {name} will be referred to in the second person (as 'you'). Do not include any dialogue or other characters' thoughts or speech. You may describe the place from {name}'s point of view, what {name} sees, and how it makes {name} feel, using words from the extract.

It is imperative that you preserve as much of the phraseology and descriptive vocabulary as possible, and that you don't introduce your own wording where there is one already given. However, you should ignore page numbers and the formatting of the extract.

Write just one paragraph of prelude. Don't give away what happens in the extract.

[BEGIN EXTRACT]
{extract}
[END EXTRACT]
'''


judge = '''
The following is an extract from a playthrough of a text adventure game. Judge how worthwhile it was for the user, along all the dimensions you think are important, and how consistent it is in its writing point of view. Combine your rating into one final rating, which will be one of "poor", "mediocre", "good", "excellent", or "outstanding". The "outstanding" rating is reserved only for the top 5%. Give the final rating in json form, like this example:

[BEGIN EXAMPLE OUTPUT]
{{ "rating: "mediocre" }}
[END EXAMPLE OUTPUT]

You can make up your own criteria. The only field that matters, and the only thing that should be given, is the final "rating". You must stick strictly to the json output format, and not give any other output.

[BEGIN EXTRACT]
{perspective}
[END EXTRACT]
'''


extract_quality = '''
The following is an extract from a story, script or essay.
Judge the writing quality as prose or as a script. Consider all relevant aspects, but give particular weight to the dialogue. Give one final rating, which will be one of "awful", "poor", "mediocre", "good", "excellent", or "outstanding". The "outstanding" rating is reserved only for the top 5%. Give indecipherable nonsense the "awful" rating. Give the final rating in json form, like this example:

[BEGIN EXAMPLE OUTPUT]
{{ "extract_quality": "mediocre" }}
[END EXAMPLE OUTPUT]

The only field that matters, and the only thing that should be given, is the final "extract_quality" rating. You must stick strictly to the json output format, and not give any other output.

[BEGIN EXTRACT]
{extract}
[END EXTRACT]
'''


bbfc = '''
The following is an extract from a story, script or essay. You will rate the text according to the BBFC rating criteria for films. Each category should be rated one of "U", "PG", "12", "15", "18", "R18" or "BAN". Last, combine the rating into one final bbfc rating.
Give your ratings in json form, like this example:

[BEGIN EXAMPLE OUTPUT]
{{
    "bbfc_behaviour": "12",
    "bbfc_discrimination": "12",
    "bbfc_drugs": "15",
    "bbfc_language": "U",
    "bbfc_sex": "U",
    "bbfc_sexual_violence": "U",
    "bbfc_horror": "U",
    "bbfc_violence": "U",
    "bbfc_rating": "15"
}}
[END EXAMPLE OUTPUT]

You must stick strictly to the json output format, and not give any other output.

[BEGIN EXTRACT]
{extract}
[END EXTRACT]
'''
