topic = '''
Below is some text from which you must create a topic summary.
Your sole purpose is to express the topic of conversation in one short phrase.

[BEGIN TEXT]
{text}
[END TEXT]
'''


bullet = '''
Below is some text from which you must create a list of bullet points that summarizes it.
Summarize the text as a markdown list, preserving the most interesting, pertinent and important points.
Your sole purpose is to summarize the conversation into bullet points.

[BEGIN TEXT]
{text}
[END TEXT]
'''


paragraph = '''
Below is some text from which you must create a summary paragraph.
Please concisely rewrite the following text, preserving the most interesting, pertinent and important points.
Your sole purpose is to summarize the conversation into a single paragraph.

[BEGIN TEXT]
{text}
[END TEXT]
'''


query = '''
Below is some text from which you must answer a query.

The query is: {query}

[BEGIN TEXT]
{text}
[END TEXT]
'''


complete_json = '''
Below is some contextual information and a JSON template to complete. You must stick very closely to the format of the template.
Use the given context to complete the template.
Complete the template, giving only valid JSON, no other text, context or explanation.

[BEGIN CONTEXT]
{context}
[END CONTEXT]

[BEGIN TEMPLATE]
{json}
[END TEMPLATE]
'''
